language: emacs-lisp
sudo: false
cache:
- directories:
  - "$HOME/emacs"
env:
  global:
  - EMAKE_SHA1=f1a50c20c36a4141ff854c5d62e1a75bb7e9ebe8
  - EMACS_DIR=$HOME/emacs
  - EMACS=$HOME/emacs/src/emacs
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
before_install:
  - make setup
install:
  - make install
script:
  - make test         # test uncompiled
  - make compile
  - make test         # test compiled
